/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Mapa;

import Personajes.Enemigo;
import java.awt.Component;
import java.awt.Image;
import java.awt.image.BufferedImage;
import javax.swing.AbstractListModel;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JToggleButton;
import javax.swing.ListCellRenderer;
import javax.swing.SpinnerNumberModel;
import javax.swing.event.ChangeEvent;

/**
 *
 * @author David Campos Rodríguez <david.campos@rai.usc.es>
 */
public class PropiedadesCelda extends javax.swing.JFrame {
    private final Celda celda;
    /**
     * Creates new form PropiedadesCelda
     */
    public PropiedadesCelda(Celda celda) {
        this.celda = celda;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panGeneral = new javax.swing.JPanel();
        tbtTransitable = new javax.swing.JToggleButton();
        lblCoordenadas = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        spnTipo = new javax.swing.JSpinner();
        lblIconoCelda = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstEnemigos = new javax.swing.JList();
        btnEngadir = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        panAceptarCancelar = new javax.swing.JPanel();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Propiedades de la celda");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Menus/ico_map.png")).getImage());
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        tbtTransitable.setSelected(celda instanceof Transitable);
        tbtTransitable.setText(celda instanceof Transitable?"Transitable":"No transitable");
        tbtTransitable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtTransitableActionPerformed(evt);
            }
        });

        lblCoordenadas.setText(String.format("Celda en (%d, %d)", celda.getMapa().getPosDe(celda).x, celda.getMapa().getPosDe(celda).y)
        );

        jLabel1.setText("Tipo:");

        spnTipo.setModel(new javax.swing.SpinnerNumberModel(celda.tipo, 0, celda instanceof Transitable?ConstantesMapa.CE_REPG_TRANS.length-1:ConstantesMapa.CE_REPG_NOTRANS.length-1, 1));
        spnTipo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnTipoStateChanged(evt);
            }
        });

        lblIconoCelda.setBackground(new java.awt.Color(0, 0, 0));
        lblIconoCelda.setIcon(new ImageIcon(new ImageIcon("img/"+celda.representacionGrafica()+".png").getImage().getScaledInstance(70, 70, Image.SCALE_SMOOTH)));
        lblIconoCelda.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.darkGray, java.awt.Color.black));

        lstEnemigos.setModel(new ModeloListaEnemigos(celda));
        lstEnemigos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstEnemigos.setCellRenderer(new RenderizadorListaEnemigos());
        jScrollPane1.setViewportView(lstEnemigos);

        btnEngadir.setText("+");
        btnEngadir.setEnabled(celda instanceof Transitable);

        btnEliminar.setText("-");
        btnEliminar.setEnabled(false);

        javax.swing.GroupLayout panGeneralLayout = new javax.swing.GroupLayout(panGeneral);
        panGeneral.setLayout(panGeneralLayout);
        panGeneralLayout.setHorizontalGroup(
            panGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panGeneralLayout.createSequentialGroup()
                .addGroup(panGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panGeneralLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnEngadir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar))
                    .addGroup(panGeneralLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE)
                            .addGroup(panGeneralLayout.createSequentialGroup()
                                .addComponent(tbtTransitable, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblCoordenadas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(spnTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblIconoCelda, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        panGeneralLayout.setVerticalGroup(
            panGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tbtTransitable)
                        .addComponent(lblCoordenadas))
                    .addComponent(lblIconoCelda, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(spnTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEliminar)
                    .addComponent(btnEngadir))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panAceptarCancelarLayout = new javax.swing.GroupLayout(panAceptarCancelar);
        panAceptarCancelar.setLayout(panAceptarCancelarLayout);
        panAceptarCancelarLayout.setHorizontalGroup(
            panAceptarCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panAceptarCancelarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAceptar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar))
        );
        panAceptarCancelarLayout.setVerticalGroup(
            panAceptarCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panAceptarCancelarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panAceptarCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnAceptar)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panAceptarCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panAceptarCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void tbtTransitableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtTransitableActionPerformed
        JToggleButton btn = (JToggleButton) evt.getSource();
        btn.setText(btn.isSelected()?"Transitable":"No transitable");
        spnTipo.setModel(new javax.swing.SpinnerNumberModel(0, 0, btn.isSelected()?ConstantesMapa.CE_REPG_TRANS.length-1:ConstantesMapa.CE_REPG_NOTRANS.length-1, 1));
        spnTipoStateChanged(new ChangeEvent(spnTipo));
        btnEngadir.setEnabled(btn.isSelected());
    }//GEN-LAST:event_tbtTransitableActionPerformed

    private void spnTipoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnTipoStateChanged
        int i = ((SpinnerNumberModel)spnTipo.getModel()).getNumber().intValue();
        if(i<0) return;
        String representacion;
        if(tbtTransitable.isSelected()){
            if(i >= ConstantesMapa.CE_REPG_TRANS.length) return;
            representacion = ConstantesMapa.CE_REPG_TRANS[i];
        }else{
            if(i >= ConstantesMapa.CE_REPG_NOTRANS.length) return;
            representacion = ConstantesMapa.CE_REPG_NOTRANS[i];
        }
        lblIconoCelda.setIcon(new ImageIcon(new ImageIcon("img/"+representacion+".png").getImage().getScaledInstance(70, 70, Image.SCALE_SMOOTH)));
    }//GEN-LAST:event_spnTipoStateChanged

    public void main() {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PropiedadesCelda.this.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEngadir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCoordenadas;
    private javax.swing.JLabel lblIconoCelda;
    private javax.swing.JList lstEnemigos;
    private javax.swing.JPanel panAceptarCancelar;
    private javax.swing.JPanel panGeneral;
    private javax.swing.JSpinner spnTipo;
    private javax.swing.JToggleButton tbtTransitable;
    // End of variables declaration//GEN-END:variables
}
class ModeloListaEnemigos extends AbstractListModel<Enemigo>{
    Transitable celda;
    public ModeloListaEnemigos(Celda c) {
        if(c instanceof Transitable)
            celda = (Transitable)c;
        else
            celda = null;
    }
    
    @Override
    public int getSize() {
        if(celda != null)
            return celda.getNumEnemigos();
        else
            return 0;
    }

    @Override
    public Enemigo getElementAt(int index) {
        if(celda != null)
            return celda.getEnemigo(index);
        else
            return null;
    }
    
}

class RenderizadorListaEnemigos extends JLabel implements ListCellRenderer<Enemigo> {
    @Override
    public Component getListCellRendererComponent(
      JList<? extends Enemigo> list,           // the list
      Enemigo enemigo,            // value to display
      int index,               // cell index
      boolean isSelected,      // is the cell selected
      boolean cellHasFocus)    // does the cell have focus
    {
        if(enemigo == null)
            setText("null");
        else{
            setText(
                    enemigo.getNombre() + "[ "
                    +(enemigo.tieneArmas()?"+"+enemigo.getEfectoArmas()+"A , ":"")
                    +(enemigo.getArmadura()!=null?"+"+enemigo.getArmadura().getDefensa()+"\u2666 , ":"")
                    +enemigo.getVida()+"\u2665 , "
                    +enemigo.getEnergia()+"E ] "
            );
        }
        if (isSelected) {
            setBackground(list.getSelectionBackground());
            setForeground(list.getSelectionForeground());
        } else {
            setBackground(list.getBackground());
            setForeground(list.getForeground());
        }
        setEnabled(list.isEnabled());
        setFont(list.getFont());
        setOpaque(true);
        return this;
    }
}